language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t soheilr/docker-react -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true soheilr/docker-react npm test
    
after_success: 
  - docker build -t soheilr/multi-client ./client
  - docker build -t soheilr/multi-nginx ./nginx
  - docker build -t soheilr/multi-server ./server
  - docker build -t soheilr/multi-worker ./worker
# Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push soheilr/multi-client 
  - docker push soheilr/multi-nginx 
  - docker push soheilr/multi-server
  - docker push soheilr/multi-worker 


deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "multi-docker"
  env: "Multi-docker-env"
  bucket_name: "elasticbeanstalk-eu-north-1-880115758046"
  bucket_path: "third_docker_multi"
  on:
    branch: master
  acess_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"