language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t soheilr/docker-react -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true soheilr/docker-react npm run test
    
after_success: 
  - docker build -t soheilr/multi-client ./client
  - docker build -t soheilr/multi-nginx ./nginx
  - docker build -t soheilr/multi-server ./server
  - docker build -t soheilr/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker log -u "$DOCKER_ID" --password-stdin