language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t soheilr/docker-react -f ./client/Dockerfile.dev .

script:
  - docker run -e CI=true soheilr/docker-react npm run test
    
    
