version: '3'
services:
  client:
    stdin_open: true
    image: "soheilr/multi-client"
    volumes:
      - /app/node_modules
      - ./client:/app
  api:
    image: "soheilr/multi-server"
    volumes:
      - /app/node_modules
      - ./server:/app
  worker:
    image: "soheilr/multi-worker"
    volumes:
      - /app/node_modules
      - ./worker:/app
  nginx:
    image: "soheilr/multi-nginx"
    depends_on:
      - api
      - client
    restart: always
    ports:
      - '80:80'
  

