version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: 'redis:latest'
  client:
    stdin_open: true
    image: "soheilr/multi-client"
    volumes:
      - /app/node_modules
      - ./client:/app
  api:
    image: "soheilr/multi-server"
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=postgres
      - PGUSER=postgres
      - PGHOST=redis
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  worker:
    image: "soheilr/multi-worker"
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  nginx:
    image: "soheilr/multi-nginx"
    depends_on:
      - api
      - client
    restart: always
    ports:
      - '80:80'
  

