version: '3'
services:
  client:
    stdin_open: true
    image: "soheilr/multi-client"
    volumes:
      - /app/node_modules
      - ./client:/app
  api:
    image: "soheilr/multi-server"
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: "soheilr/multi-worker"
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: "soheilr/multi-nginx"
    links:
      - api
      - client
    restart: always
    ports:
      - '80:80'
  

