version: '3'
services:
  client:
    stdin_open: true
    image: "soheilr/multi-client"
    volumes:
      - /app/node_modules
      - ./client:/app
  api:
    image: "soheilr/multi-server"
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=docker-multi-redis.f96tsq.clustercfg.eun1.cache.amazonaws.com
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=multi-docker.cypy0wdy0nvq.eu-north-1.rds.amazonaws.com
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  worker:
    image: "soheilr/multi-worker"
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=docker-multi-redis.f96tsq.clustercfg.eun1.cache.amazonaws.com

      - REDIS_PORT=6379
  nginx:
    image: "soheilr/multi-nginx"
    depends_on:
      - api
      - client
    restart: always
    ports:
      - '80:80'
  

