version: '3'
services:
  postgres:
    image: 'postgres:latest'
  redis:
    image: 'redis:latest'
  nginx:
    depends_on:
      - api
      - client
    restart: always
    image: soheilr/multi-nginx
    ports:
      - '80:80'
  api:
    image: soheilr/multi-server
    volumes:
      - /app/node_modules
      - ./server:/app
  client:
    stdin_open: true
    image: soheilr/multi-client
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    image: soheilr/multi-worker
    volumes:
      - /app/node_modules
      - ./worker:/app